# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e20269ae18bb623d209168148e61503c86dd3322594d951c22180e15a1ff827ef2fb3e06eeba2749923a22c57520588206fc5faeae0091d39e201eb11c3f4e00

test:
  secret_key_base: 9813244e28814e3dd2ad3e367d40af1f2e9b83884af26a9fbd5d077080c46afd97565dc6b227e8d8ccd27c1adc7a3120dbfbd537513374647803eca10c3fb732

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
